"""Add may use participants column

Revision ID: 004021a245dd
Revises: 979fdcc03d57
Create Date: 2025-02-07 00:51:03.506239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004021a245dd'
down_revision = '979fdcc03d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('may_use_participants', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_role', schema=None) as batch_op:
        batch_op.drop_column('may_use_participants')

    # ### end Alembic commands ###
