"""Add privilege:manage_users

Revision ID: 008c014f0c23
Revises: 72e0dd2ea3b3
Create Date: 2022-12-18 01:28:52.568939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008c014f0c23'
down_revision = '72e0dd2ea3b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('may_manage_users', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'may_manage_users')
    # ### end Alembic commands ###
