"""Add estimated fight count property to list systems

Revision ID: 041afafa2f97
Revises: 0de4b8f4bece
Create Date: 2024-01-11 20:32:47.300090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041afafa2f97'
down_revision = '0de4b8f4bece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list_system', sa.Column('estimated_fight_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('list_system', 'estimated_fight_count')
    # ### end Alembic commands ###
