"""Add team member model

Revision ID: 0c8a41993f2a
Revises: 4df9e26e63bc
Create Date: 2024-10-25 19:11:41.787576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8a41993f2a'
down_revision = '4df9e26e63bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=80), nullable=True),
    sa.Column('association_name', sa.String(length=80), nullable=True),
    sa.Column('removed', sa.Boolean(), nullable=True),
    sa.Column('disqualified', sa.Boolean(), nullable=True),
    sa.Column('removal_cause', sa.Text(length=250), nullable=True),
    sa.Column('last_fight_at', sa.DateTime(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('row_id', sa.Integer(), nullable=True),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['registration.id'], ),
    sa.ForeignKeyConstraint(['row_id'], ['team_row.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_member')
    # ### end Alembic commands ###
