"""Add list tags to match

Revision ID: 0de4b8f4bece
Revises: e16be8e70829
Create Date: 2023-12-16 02:25:42.735724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de4b8f4bece'
down_revision = 'e16be8e70829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_tags', sa.String(length=85), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('list_tags')

    # ### end Alembic commands ###
