"""Add light/dark mode preference

Revision ID: 101fdae61dd2
Revises: 9b0f73c854bd
Create Date: 2022-12-25 17:28:00.802763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101fdae61dd2'
down_revision = '9b0f73c854bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefers_dark_mode', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('prefers_dark_mode')

    # ### end Alembic commands ###
