"""add devices, event roles, allow- field

Revision ID: 10c15208ca02
Revises: 6fc7347b5a20
Create Date: 2023-05-14 19:45:08.848856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c15208ca02'
down_revision = '6fc7347b5a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('may_use_registration', sa.Boolean(), nullable=True),
    sa.Column('may_use_weigh_in', sa.Boolean(), nullable=True),
    sa.Column('may_use_placement_tool', sa.Boolean(), nullable=True),
    sa.Column('may_use_global_list', sa.Boolean(), nullable=True),
    sa.Column('may_use_assigned_lists', sa.Boolean(), nullable=True),
    sa.Column('may_use_scoreboard', sa.Boolean(), nullable=True),
    sa.Column('may_use_display', sa.Boolean(), nullable=True),
    sa.Column('may_use_results', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('device_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('token', sa.String(length=60), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('registered_by_id', sa.Integer(), nullable=True),
    sa.Column('event_role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['event_role_id'], ['event_role.id'], ),
    sa.ForeignKeyConstraint(['registered_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_device_registration', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('allow_device_registration')

    op.drop_table('device_registration')
    op.drop_table('event_role')
    # ### end Alembic commands ###
