"""Add team registration model

Revision ID: 10e4dca47c46
Revises: 7ad42abbc90d
Create Date: 2024-10-12 22:33:05.282586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e4dca47c46'
down_revision = '7ad42abbc90d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=80), nullable=True),
    sa.Column('club', sa.String(length=150), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('event_class_id', sa.Integer(), nullable=True),
    sa.Column('association_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('placed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('registered', sa.Boolean(), nullable=True),
    sa.Column('placed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['association_id'], ['association.id'], ),
    sa.ForeignKeyConstraint(['event_class_id'], ['event_class.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_registration')
    # ### end Alembic commands ###
