"""prepare automation and group name gen

Revision ID: 1111e8826d3a
Revises: 04e843eade42
Create Date: 2023-11-25 23:47:38.119259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1111e8826d3a'
down_revision = '04e843eade42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_title', sa.String(length=30), nullable=True))

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_manually', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('assign_by_logic', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('min_weight', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_weight', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('max_weight')
        batch_op.drop_column('min_weight')
        batch_op.drop_column('assign_by_logic')
        batch_op.drop_column('created_manually')

    with op.batch_alter_table('event_class', schema=None) as batch_op:
        batch_op.drop_column('short_title')

    # ### end Alembic commands ###
