"""Add escalated option to help requests

Revision ID: 166afb57d575
Revises: ef44f684c321
Create Date: 2024-12-05 08:52:22.996553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166afb57d575'
down_revision = 'ef44f684c321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('escalated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help_request', schema=None) as batch_op:
        batch_op.drop_column('escalated')

    # ### end Alembic commands ###
