"""Add per-list page counter

Revision ID: 1cfcb55d5fac
Revises: 825cb1796514
Create Date: 2025-03-27 00:19:45.222085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cfcb55d5fac'
down_revision = '825cb1796514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_page_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('display_page_count')

    # ### end Alembic commands ###
