"""add event log items

Revision ID: 1edee6fd66be
Revises: 7552fa4602c6
Create Date: 2024-05-18 19:20:12.919698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edee6fd66be'
down_revision = '7552fa4602c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_log_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('log_type', sa.String(length=50), nullable=True),
    sa.Column('log_value', sa.Text(), nullable=True),
    sa.Column('log_creator', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_log_item')
    # ### end Alembic commands ###
