"""Add last used timestamp to groups

Revision ID: 2c2c2d2ebbae
Revises: f6c4f7f0c3fd
Create Date: 2024-03-24 15:16:04.763304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2c2d2ebbae'
down_revision = 'f6c4f7f0c3fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_used_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('last_used_at')

    # ### end Alembic commands ###
