"""Add device positions to matches

Revision ID: 42a0f2b64fcc
Revises: 1cfcb55d5fac
Create Date: 2025-05-10 18:31:22.303645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a0f2b64fcc'
down_revision = '1cfcb55d5fac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_position_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("match_on_device_position", 'device_position', ['device_position_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_constraint("match_on_device_position", type_='foreignkey')
        batch_op.drop_column('device_position_id')

    # ### end Alembic commands ###
