"""add confirmed option to device registrations

Revision ID: 432227af434c
Revises: 10c15208ca02
Create Date: 2023-05-14 22:46:30.374137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432227af434c'
down_revision = '10c15208ca02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_registration', schema=None) as batch_op:
        batch_op.drop_column('confirmed')
        batch_op.drop_column('confirmed_at')

    # ### end Alembic commands ###
