"""Add events table

Revision ID: 4502933af8c3
Revises: 101fdae61dd2
Create Date: 2023-01-22 21:59:47.713896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4502933af8c3'
down_revision = '101fdae61dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('slug', sa.String(length=65), nullable=True),
    sa.Column('first_day', sa.DateTime(), nullable=True),
    sa.Column('last_day', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
