"""Add team row class

Revision ID: 4df9e26e63bc
Revises: adce47999af1
Create Date: 2024-10-25 19:11:09.776436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4df9e26e63bc'
down_revision = 'adce47999af1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=True),
    sa.Column('match_order_key', sa.Integer(), nullable=True),
    sa.Column('created_manually', sa.Boolean(), nullable=True),
    sa.Column('assign_by_logic', sa.Boolean(), nullable=True),
    sa.Column('min_weight', sa.Integer(), nullable=True),
    sa.Column('max_weight', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('event_class_id', sa.Integer(), nullable=True),
    sa.Column('lower_row_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_class_id'], ['event_class.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['lower_row_id'], ['team_row.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_row')
    # ### end Alembic commands ###
