"""Add further scheduling attributes to groups

Revision ID: 5189300e25bd
Revises: 42a0f2b64fcc
Create Date: 2025-05-10 18:34:10.709319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5189300e25bd'
down_revision = '42a0f2b64fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_break_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_for', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('scheduled_for')
        batch_op.drop_column('list_break_count')

    # ### end Alembic commands ###
