"""Add TeamNameGenerator class

Revision ID: 62e805870e8a
Revises: 0c8a41993f2a
Create Date: 2024-11-27 15:35:58.279328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e805870e8a'
down_revision = '0c8a41993f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_name_generator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('items', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_name_generator')
    # ### end Alembic commands ###
