"""Add event classes

Revision ID: 6fc7347b5a20
Revises: fb80585ec71b
Create Date: 2023-05-13 22:09:08.960932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc7347b5a20'
down_revision = 'fb80585ec71b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('begin_weigh_in', sa.Boolean(), nullable=True),
    sa.Column('begin_weigh_in_at', sa.DateTime(), nullable=True),
    sa.Column('begin_placement', sa.Boolean(), nullable=True),
    sa.Column('begin_placement_at', sa.DateTime(), nullable=True),
    sa.Column('begin_fighting', sa.Boolean(), nullable=True),
    sa.Column('begin_fighting_at', sa.DateTime(), nullable=True),
    sa.Column('ended_fighting', sa.Boolean(), nullable=True),
    sa.Column('ended_fighting_at', sa.DateTime(), nullable=True),
    sa.Column('fighting_time', sa.Integer(), nullable=True),
    sa.Column('golden_score_time', sa.Integer(), nullable=True),
    sa.Column('between_fights_time', sa.Integer(), nullable=True),
    sa.Column('use_proximity_weight_mode', sa.Boolean(), nullable=True),
    sa.Column('default_maximal_proximity', sa.Integer(), nullable=True),
    sa.Column('weight_generator', sa.Text(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_class')
    # ### end Alembic commands ###
