"""Add privilege:may_create_tournament

Revision ID: 72e0dd2ea3b3
Revises: 54cc5a06923a
Create Date: 2022-12-18 01:11:23.177580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e0dd2ea3b3'
down_revision = '54cc5a06923a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('may_create_tournaments', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'may_create_tournaments')
    # ### end Alembic commands ###
