"""Add sb rulesets to events

Revision ID: 78e89668c9b9
Revises: 6c7750ab0b67
Create Date: 2024-12-15 20:48:42.368330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e89668c9b9'
down_revision = '6c7750ab0b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scoreboard_ruleset_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('sb_ruleset_on_event', 'scoreboard_ruleset', ['scoreboard_ruleset_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint('sb_ruleset_on_event', type_='foreignkey')
        batch_op.drop_column('scoreboard_ruleset_id')

    # ### end Alembic commands ###
