"""add template options to event_class

Revision ID: 7fe3799d53cc
Revises: 9fc0ffe2f89a
Create Date: 2023-05-28 14:43:01.157885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe3799d53cc'
down_revision = '9fc0ffe2f89a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_template', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('template_name', sa.String(length=75), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_class', schema=None) as batch_op:
        batch_op.drop_column('template_name')
        batch_op.drop_column('is_template')

    # ### end Alembic commands ###
