"""Add obsolete flag

Revision ID: 80645a7bd8c3
Revises: fd6085a628a4
Create Date: 2024-07-31 13:35:13.678604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80645a7bd8c3'
down_revision = 'fd6085a628a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('obsolete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('obsolete')

    # ### end Alembic commands ###
