"""Add match no

Revision ID: 825cb1796514
Revises: 004021a245dd
Create Date: 2025-03-22 22:12:44.626917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825cb1796514'
down_revision = '004021a245dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_list_no', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('match_list_no')

    # ### end Alembic commands ###
