"""Add default column to ScoreboardRuleset

Revision ID: 979fdcc03d57
Revises: 78e89668c9b9
Create Date: 2024-12-16 23:40:07.843414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979fdcc03d57'
down_revision = '78e89668c9b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scoreboard_ruleset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scoreboard_ruleset', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
