"""auto-migrate

Revision ID: 9b0f73c854bd
Revises: c42d9efd48dc
Create Date: 2022-12-25 17:27:46.123159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0f73c854bd'
down_revision = 'c42d9efd48dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('fs_uniquifier',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('display_name',
               existing_type=sa.TEXT(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('display_name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(length=50),
               existing_nullable=True)
        batch_op.alter_column('fs_uniquifier',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
