"""Add percentage instead of absolute column for proximity weight mode

Revision ID: a813ceb2879a
Revises: f5adefadaf08
Create Date: 2024-05-28 13:24:11.252437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a813ceb2879a'
down_revision = 'f5adefadaf08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proximitiy_uses_percentage_instead_of_absolute', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_class', schema=None) as batch_op:
        batch_op.drop_column('proximitiy_uses_percentage_instead_of_absolute')

    # ### end Alembic commands ###
