"""Add team_registration column to registration

Revision ID: adce47999af1
Revises: fcb3696f5c43
Create Date: 2024-10-16 18:24:19.054056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adce47999af1'
down_revision = 'fcb3696f5c43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_registration_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('team_registration_on_registration', 'team_registration', ['team_registration_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.drop_constraint('team_registration_on_registration', type_='foreignkey')
        batch_op.drop_column('team_registration_id')

    # ### end Alembic commands ###
