"""add default max size for proximity mode

Revision ID: b33a69452dc5
Revises: bbc20f039789
Create Date: 2023-05-28 17:23:49.635328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33a69452dc5'
down_revision = 'bbc20f039789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_maximal_size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_class', schema=None) as batch_op:
        batch_op.drop_column('default_maximal_size')

    # ### end Alembic commands ###
