"""add may_alter_presets priv

Revision ID: bbc20f039789
Revises: 7fe3799d53cc
Create Date: 2023-05-28 15:41:28.977197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc20f039789'
down_revision = '7fe3799d53cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('may_alter_presets', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('may_alter_presets')

    # ### end Alembic commands ###
