"""Add implementation options to Group/Participant

Revision ID: ccb96413478f
Revises: 11deba148794
Create Date: 2023-12-12 17:52:19.561211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb96413478f'
down_revision = '11deba148794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('assigned_to_position_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('marked_ready', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('marked_ready_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('opened', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('opened_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('device_position_id', 'device_position', ['assigned_to_position_id'], ['id'])

    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_fight_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_column('last_fight_at')

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint('device_position_id', type_='foreignkey')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('completed')
        batch_op.drop_column('opened_at')
        batch_op.drop_column('opened')
        batch_op.drop_column('marked_ready_at')
        batch_op.drop_column('marked_ready')
        batch_op.drop_column('assigned_to_position_id')
        batch_op.drop_column('assigned')

    # ### end Alembic commands ###
