"""Add fields for listlib connection

Revision ID: e16be8e70829
Revises: ccb96413478f
Create Date: 2023-12-16 02:00:32.180152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e16be8e70829'
down_revision = 'ccb96413478f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('random_seed', sa.Integer(), nullable=True))

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_playoff', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('is_playoff')

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('random_seed')

    # ### end Alembic commands ###
