"""Add 'currently used' group option

Revision ID: f3c953231c08
Revises: 1e65b96f9e0c
Create Date: 2024-03-26 14:32:25.443696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c953231c08'
down_revision = '1e65b96f9e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currently_used', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('currently_used')

    # ### end Alembic commands ###
