"""Add display page count to list system database

Revision ID: f5adefadaf08
Revises: 1edee6fd66be
Create Date: 2024-05-21 19:30:52.122075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5adefadaf08'
down_revision = '1edee6fd66be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_system', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_page_count', sa.Integer(), nullable=True))

    # Backfill default value
    op.execute('UPDATE list_system SET display_page_count=1;')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_system', schema=None) as batch_op:
        batch_op.drop_column('display_page_count')

    # ### end Alembic commands ###
