"""Add supervisor columns

Revision ID: fb80585ec71b
Revises: 4502933af8c3
Create Date: 2023-01-23 09:25:13.343986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb80585ec71b'
down_revision = '4502933af8c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supervising_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('supervising_role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('event_supervisor_role_constraint', 'role', ['supervising_role_id'], ['id'])
        batch_op.create_foreign_key('event_supervisor_user_constraint', 'user', ['supervising_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint('event_supervisor_role_constraint', type_='foreignkey')
        batch_op.drop_constraint('event_supervisor_user_constraint', type_='foreignkey')
        batch_op.drop_column('supervising_role_id')
        batch_op.drop_column('supervising_user_id')

    # ### end Alembic commands ###
