"""Fix spelling + add group count columns

Revision ID: fd6085a628a4
Revises: a813ceb2879a
Create Date: 2024-06-19 22:50:58.654040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd6085a628a4'
down_revision = 'a813ceb2879a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_maximal_group_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('proximity_prefer_group_count_over_proximity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('proximity_uses_percentage_instead_of_absolute', sa.Boolean(), nullable=True))
        batch_op.drop_column('proximitiy_uses_percentage_instead_of_absolute')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proximitiy_uses_percentage_instead_of_absolute', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('proximity_uses_percentage_instead_of_absolute')
        batch_op.drop_column('proximity_prefer_group_count_over_proximity')
        batch_op.drop_column('default_maximal_group_count')

    # ### end Alembic commands ###
